basePath: /
definitions:
  handler.HealthCheckResponse:
    properties:
      database_status:
        type: string
      server_status:
        type: string
      timestamp:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a simple API for tracking daily vibes.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Daily Vibe Tracker API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check the health of the API and database connection.
      produces:
      - application/json
      responses:
        "200":
          description: Successfully checked health
          schema:
            $ref: '#/definitions/handler.HealthCheckResponse'
        "503":
          description: Service unavailable if database ping fails
          schema:
            $ref: '#/definitions/handler.HealthCheckResponse'
      summary: API Health Check
      tags:
      - Health
schemes:
- http
- https
swagger: "2.0"
